version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-to-do"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1do8zzi3dg4t2"
s3_prefix = "serverless-to-do"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
